
services:
  - type: web
    plan: free
    name: GPT
    env: python
    buildCommand: pip install -U -r requirements.txt
    startCommand: python3 ser.py & python3 main.py 
    region: frankfurt
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: GOOGLE_API_KEY 
        sync: false
